// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  call_to_action: defineAsyncComponent(
    () => import("./CallToAction/index.vue"),
  ),
  finish_page: defineAsyncComponent(() => import("./FinishPage/index.vue")),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  hero_2: defineAsyncComponent(() => import("./Hero2/index.vue")),
  insured_information: defineAsyncComponent(
    () => import("./InsuredInformation/index.vue"),
  ),
  navigation_bar: defineAsyncComponent(
    () => import("./NavigationBar/index.vue"),
  ),
  pricing_step: defineAsyncComponent(() => import("./PricingStep/index.vue")),
  summary_information: defineAsyncComponent(
    () => import("./SummaryInformation/index.vue"),
  ),
  trip_information_step: defineAsyncComponent(
    () => import("./TripInformationStep/index.vue"),
  ),
});
